name: Android Pull Request Testsuite

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  lint_and_unittest:
    name: Lint and Unit testsuite
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: |
          cd AntiCovid/ 
          chmod +x ./gradlew

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Run Lint
        run: |
          cd AntiCovid/
          ./gradlew lint

      - name: Run Unit Test
        run: |
          cd AntiCovid/
          ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

